### ISSUE TITLE
Seeking for help about training code

### ISSUE THREAD

**Issue by Byastal** [ktrk115/const_layout#1]
Hello, could you provide the LayoutGan training code?(not LayoutGANpp)

**Comment by ktrk115** [comment]
Currently, I have no plan to release my dirty LayoutGAN code.
The following repositories seem to be maintained and could be helpful.
- https://github.com/Layout-Generation/layout-generation/tree/master/LayoutGAN
- https://github.com/TakaoNarikawa/LayoutGAN-Reimplementation
