### ISSUE TITLE
python generate.py提示内存溢出，但内存确实是充足的，大家有遇到相似情况吗

### ISSUE THREAD

**Issue by panpan73** [ktrk115/const_layout#11]
（1）python generate.py
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

（2）内存情况

![image](https://user-images.githubusercontent.com/103486878/185053618-66dfd15a-4f4d-4bd2-b9fe-19e7b673b33e.png)

**Comment by ktrk115** [comment]
As seen in #12, your environment may not be set up properly. Please read the README carefully and try it again.
