### ISSUE TITLE
about the train loss

### ISSUE THREAD

**Issue by Usernamezhx** [ktrk115/const_layout#13]
thank for you work. I train the model with command:
```python
python train.py --dataset rico --batch_size 64 --iteration 200000 --latent_size 4 --lr 1e-05 --G_d_model 256 --G_nhead 4 --G_num_layers 8 --D_d_model 256 --D_nhead 4 --D_num_layers 8
```
**and it will show me that. does it look normal ? the generator loss become large and Discriminator loss become small :**
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/14010625/195806803-416e2984-b8b8-4347-8b3e-6b99fc7126e2.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/14010625/195807377-fb7516d0-ff1f-480b-8734-8c1796d2f13e.png">

**Comment by ktrk115** [comment]
Sorry for the late response.

The generator seems relatively weak, but I think it is a natural behavior. You may update the generator two or more times for each update of the discriminator. The number of updates is a tunable hyperparameter.

**Comment by Usernamezhx** [comment]
> Sorry for the late response.
> 
> The generator seems relatively weak, but I think it is a natural behavior. You may update the generator two or more times for each update of the discriminator. The number of updates is a tunable hyperparameter.

thanks for your reply. I will try
