### ISSUE TITLE
Why add "to_dense_batch" to process the location information x and category label y?

### ISSUE THREAD

**Issue by MtYCNN** [ktrk115/const_layout#14]
What does this mean, please? Why add "to_dense_batch" to process the location information x and category label y?

 for i, data in enumerate(train_dataloader):
            data = data.to(device)
            label, mask = to_dense_batch(data.y, data.batch)#？？？？？？？？？？？？？？？
            bbox_real, _ = to_dense_batch(data.x, data.batch)#？？？？？？？？？？？？？？？

**Comment by ktrk115** [comment]
Check [this PyG doc](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.to_dense_batch).
