### ISSUE TITLE
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm

### ISSUE THREAD

**Issue by WuChannn** [ktrk115/const_layout#15]
@ktrk115 hi, when i run the train code, I came across the problem as the title list. my environmet is :

torch                   1.8.1+cu111
torch-geometric         1.7.2
torch-scatter           2.0.7
torch-sparse            0.6.10
torchaudio              0.8.1
torchvision             0.9.1+cu111

and I install pytorch with: `pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`

if i install pytorch with `conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge`, I can not use gpu, for there is always cpu version pytorch

look forward to your reply.

**Comment by ktrk115** [comment]
Can you show me the entire error message?
