### ISSUE TITLE
furniture placement

### ISSUE THREAD

**Issue by StephenZhao1** [ktrk115/const_layout#17]
I am on a project concerning furniture placement in a room，the target is place some furnitures in a room.The input is like
![image](https://user-images.githubusercontent.com/38208848/223909995-654a6ba3-5766-45d5-86d9-df0ee8e8425f.png).The image includes wall, window and door line segments, the room shape not only rectangle but also polygon with right angle.

1. how can I change the input with any shape?
2. how can I consider the window and door into model，because window and door has a big connection with furniture placement

Thx a lot, look forward to your response

**Comment by ktrk115** [comment]
I have no idea how to use polygon instead of bbox input. Sorry.
