### ISSUE TITLE
how to use the model with local dataset?

### ISSUE THREAD

**Issue by slr1997** [ktrk115/const_layout#21]
I want to train it with local dataset, how to train the LayoutFID model? Could you provide the training codes?

**Comment by Pppotatoo** [comment]
I wonder too.Have you reslove this question?

**Comment by ktrk115** [comment]
You can refer to the training code for the FID model provided in [our successor project](https://github.com/CyberAgentAILab/layout-dm/tree/main/src/trainer/trainer/fid).
