### ISSUE TITLE
Question about FID

### ISSUE THREAD

**Issue by molu-ggg** [ktrk115/const_layout#23]
In the text 4.2.1, you mentioned "To compute FID, we need to define the representative features of layouts. We follow the approach of Lee et al . [16] , and train a neural network to classify between real layouts and noise added layouts, and use the intermediate features of the network. One difference from [ 16] is that we incorporate the auxiliary decoder in Sec 3.1.3 learning such that the trained network is aware of both alignment and positions."

I didn't find the publicly available code for citation [16]. The code you provided shows the structure of the model, but it doesn't offer the details of the FID training. Could you please provide the training details of this model? I'd like to conduct an evaluation on a new data set. Thank you for your help. I would be extremely grateful.

**Comment by ktrk115** [comment]
Please see here https://github.com/ktrk115/const_layout/issues/21#issue-1964986347
