### ISSUE TITLE
data link is in 404 status, how can i get the train data?

### ISSUE THREAD

**Issue by Jolinbaby** [ktrk115/const_layout#5]
Download rico_dataset_v0.1_semantic_annotations.zip from "UI Screenshots and Hierarchies with Semantic Annotations" and decompress it.
but it is
![image](https://user-images.githubusercontent.com/60809535/172882705-8c1b1cde-f415-4b87-88d9-3172874c326d.png)

**Comment by Jolinbaby** [comment]
I have solved this problem, the valid link is as follows:
https://interactionmining.org/rico#quick-downloads
you can find the dataset in it.

**Comment by ktrk115** [comment]
Thank you for your report. I'll correct the link.
