### ISSUE TITLE
7.Install ImageMagick for visualization can it be more detailed?

### ISSUE THREAD

**Issue by Jolinbaby** [ktrk115/const_layout#6]
I am a green hand in AI model, after i got these pretrained models, i don't know the next step...Please help me
![image](https://user-images.githubusercontent.com/60809535/172996170-c59d3492-de03-4ad6-a6ef-c96f6a1f5ee1.png)

**Comment by Jolinbaby** [comment]
when generated layout, i met some problems...
![image](https://user-images.githubusercontent.com/60809535/172999458-f4fc027b-d350-4f3d-8ae7-4da89b5279ae.png)

**Comment by ktrk115** [comment]
I'm afraid that I have no experience in developing on windows, so I cannot judge whether the code will work properly on windows, nor can I provide support. For the torch_sparce error, you may ask the original developers. https://github.com/rusty1s/pytorch_sparse
