### ISSUE TITLE
Key error with constrained generation

### ISSUE THREAD

**Issue by sukritiverma1996** [ktrk115/const_layout#7]
Hey,
Thanks for releasing your code and environment. I was able to generate samples using pre-trained models.
However, when I try to generate samples with constraints, I get the following key error:
```Traceback (most recent call last):
  File "generate_const.py", line 199, in <module>
    main()
  File "generate_const.py", line 148, in main
    for z in optimizer.generator(z, data):
  File "/home/sukrverm/const_layout/clg/auglag.py", line 96, in generator
    assert data.attr[0]['has_canvas_element']
KeyError: 0
```

I suppose this is some attribute of publaynet data that is False here.
Do I need to edit the get_dataset Publaynet class to remove such examples before hand?

**Comment by ktrk115** [comment]
Thank you for your interest.
It seems that the collate_fn for dictionaries has been changed after pytorch geometric 1.7.2.

There's two options to fix this:
1. edit `assert data.attr[0]['has_canvas_element']` to `assert data.attr['has_canvas_element'][0]`.
2. downgrade pytorch geometric to 1.7.2, and process the dataset again.

I recommend the latter one as it might have other unintended behaviors.

**Comment by sukritiverma1996** [comment]
Downgrading did not work out for me unfortunately. The environment would just not work and all errors pointed to upgrading geometric.
Working with the first option for now
