### ISSUE TITLE
assert data.attr[0]['has_canvas_element']

### ISSUE THREAD

**Issue by Jolinbaby** [ktrk115/const_layout#8]
![image](https://user-images.githubusercontent.com/60809535/173065352-00c825ea-9524-492f-9003-3f6a2405b85c.png)

**Comment by Jolinbaby** [comment]
this problem happened when i tryed to Generate layouts with relational constraints

**Comment by ktrk115** [comment]
Duplicated #7. Please confirm the other issues before creating new one.
