### ISSUE TITLE
How to change number of elements? 

### ISSUE THREAD

**Issue by sukritiverma1996** [ktrk115/const_layout#9]
Hey,
I've been trying to train a model on Rico with more data
In rico.py, I can see that number of elements are capped at 9

I've been going through your generator and discriminator code and I would greatly appreciate some help in where I need to make changes so the models can accept in data samples with bboxes and labels > 9. 

Thanks so much!
Sukriti

**Comment by ktrk115** [comment]
Hi Sukriti,

If I remember correctly, you don't need to edit the code for both the generator and the discriminator. The code should work with variable length of elements. To add more labels, you need to edit the following.
https://github.com/ktrk115/const_layout/blob/4090f55ad728a31e22fd1a97a79f5a82c77b38de/data/rico.py#L19-L33

If you get any results with the full Rico dataset, I would appreciate it if you could share them here or on PR.

Thanks!
Kotaro

**Comment by sukritiverma1996** [comment]
Yes, definitely
This is my first time dabbling with GANs though
Thank you!
